Serilog:
  Using: [Serilog.Sinks.Console]
  MinimumLevel:
    Default: Information
    Override:
      Microsoft: Warning
      Microsoft.Hosting.Lifetime: Information
  WriteTo:
    - Name: Console
      Args:
        OutputTemplate: "[{Timestamp:HH:mm:ss} {Level:u3} {SourceContext}] {Message:lj}{NewLine}{Exception}"
  Enrich: [FromLogContext]
AllowedHosts: admin.troyeschina.space
urls: http://127.0.0.1:27689/
WebRootPath: /opt/pirate-admin/bin/wwwroot
ForwardProxies:
  - 127.0.0.1
AuthServer: https://auth.spacestation14.com
