name: Build & Test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: 'recursive'
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v3.2.0
        with:
          dotnet-version: 9.0.x
      - name: Install dependencies
        run: dotnet restore
      - name: Publish admin panel
        run: dotnet publish SS14.Admin/SS14.Admin.csproj --configuration Release --no-restore --output publish
      - name: Upload admin panel
        uses: actions/upload-artifact@v4
        with:
          name: pirate-admin
          path: publish/
          retention-days: 7
